# Generated by Django 5.2.8 on 2025-11-30 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('APPROVER_PROD', 'Aprovador Produção'), ('APPROVER_MAINT', 'Aprovador Manutenção')], max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_description', models.TextField(verbose_name='Problema')),
                ('process', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('gut_gravity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('gut_urgency', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('gut_tendency', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='requests/')),
                ('status', models.CharField(choices=[('OPEN', 'Emitido'), ('WAITING_PROD', 'Aguardando Aprovação (Produção)'), ('WAITING_MAINT', 'Aguardando Aprovação (Manutenção)'), ('IN_EXECUTION', 'Em Execução'), ('DONE', 'Concluído'), ('REJECTED', 'Rejeitado')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_description', models.TextField(blank=True, null=True)),
                ('execution_photo', models.ImageField(blank=True, null=True, upload_to='executions/')),
                ('pm04_order', models.CharField(blank=True, max_length=50, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.maintenancerequest')),
            ],
        ),
    ]
