# Generated by Django 5.2.8 on 2025-11-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmc', models.CharField(max_length=20, unique=True, verbose_name='HMC (Matrícula)')),
                ('role', models.CharField(choices=[('REQUESTER', 'Solicitante'), ('APPROVER_PROD', 'Aprovador Produção'), ('APPROVER_MAINT', 'Aprovador Manutenção'), ('EXECUTOR', 'Executante')], default='REQUESTER', max_length=20, verbose_name='Função/Cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
