# Generated by Django 5.2.8 on 2025-12-01 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='type',
            field=models.CharField(blank=True, choices=[('TECHNICAL', 'Técnica'), ('ENGINEERING', 'Engenharia')], max_length=20, null=True, verbose_name='Tipo da Demanda'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Emitido'), ('WAITING_PROD', 'Aguardando Aprovação (Produção)'), ('WAITING_MAINT', 'Aguardando Aprovação (Manutenção)'), ('WAITING_MANAGER', 'Aguardando Gerente (Engenharia)'), ('IN_EXECUTION', 'Em Execução'), ('DONE', 'Concluído'), ('REJECTED', 'Rejeitado')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Solicitante'), ('APPROVER_PROD', 'Supervisor Produção'), ('APPROVER_MAINT', 'Supervisor Manutenção'), ('MANAGER_MAINT', 'Gerente Manutenção'), ('EXECUTOR', 'Executante (Técnico)'), ('ENGINEER_MECH', 'Engenheiro Mecânico'), ('ENGINEER_ELEC', 'Engenheiro Elétrico')], default='REQUESTER', max_length=20, verbose_name='Função/Cargo'),
        ),
    ]
