# Generated by Django 5.2.8 on 2025-12-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maintenancerequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='key',
            field=models.CharField(choices=[('APPROVER_PROD', 'Supervisor Produção'), ('APPROVER_MAINT', 'Supervisor Manutenção'), ('MANAGER_MAINT', 'Gerente Manutenção')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='execution_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Atividade'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='execution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='executions/', verbose_name='Foto da Execução'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='pm04_order',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Ordem PM04'),
        ),
    ]
