# Generated by Django 5.2.8 on 2025-12-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maintenancerequest_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Técnico Executante'),
        ),
    ]
